### ISSUE TITLE
Improvement by writing a README for your codebase

### ISSUE THREAD

**Issue by dicethedev** [Oyinade3/Dolapo-Adereti-portfolio#1]
I love your work @Oyinade3 Bad ass Frontend developer. 😂 

Improve more by adding good ReadMe to your codebase for a better explanation of what is happening in your codebase. Well done and never stop building and learning. 👌👍💕

**Comment by Oyinade3** [comment]
Thank you very much @dicethedev
I'll definitely start implementing ReadMe files now, I hope the files weren't difficult to navigate

**Comment by dicethedev** [comment]
@Oyinade3 your files are ok and straight to the point. Well done!
